### ISSUE TITLE
arm64 build currently fails

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/WSLFedoraRemix#25]
see logs here: https://gist.github.com/sirredbeard/e86cf623a12e148c92d5604cf38e82ad

**Comment by sirredbeard** [comment]
It happens at https://github.com/WhitewaterFoundry/WSLFedoraRemix/blob/development/create-targz.sh#L33:

```
[root@fedora tmp.9Yr9wwPQgH]# chroot $TMPDIR/dist dnf -y install cracklib-dicts generic-release --allowerasing
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/libdnf/conf.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libgcc_s.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dnf", line 57, in <module>
    from dnf.cli import main
  File "/usr/lib/python3.7/site-packages/dnf/__init__.py", line 30, in <module>
    import dnf.base
  File "/usr/lib/python3.7/site-packages/dnf/base.py", line 29, in <module>
    import libdnf.transaction
  File "/usr/lib64/python3.7/site-packages/libdnf/__init__.py", line 3, in <module>
    from . import conf
  File "/usr/lib64/python3.7/site-packages/libdnf/conf.py", line 17, in <module>
    _conf = swig_import_helper()
  File "/usr/lib64/python3.7/site-packages/libdnf/conf.py", line 16, in swig_import_helper
    return importlib.import_module('_conf')
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_conf'
[root@fedora tmp.9Yr9wwPQgH]#
```

Something in the change from the dnf --installroot=$TMPDIR/dist to the chroot method seems to be causing an issue for me.

I am running Fedora in HyperV.

I had no problem building x86_64 image.
